title: adVANtures
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://van-richard.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
