title: Computational Chemistry Notes
description: Guide to the world of Computational Chemistry
theme: just-the-docs

color_scheme: dark

url: https://van-richard.github.io

aux_links:
   Github Repository: https://github.com/van-richard/CompChemNotes
